# travis CI config
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - pypy3
matrix:
  fast_finish: true

# Use fast travis build infrastructure explicitly
dist: trusty
sudo: false

install:
  - pip install .
script:
  - cd tests
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then PYTHONPATH=. python -E -Wall -tt -bb -m pytest tests; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then PYTHONPATH=. python -E -Wall -bb -m pytest tests; fi
# pypy doesn't like -tt option
