# travis CI config
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - pypy3
matrix:
  fast_finish: true

# Use fast travis build infrastructure explicitly
sudo: false

install:
  - pip install .
script:
  - PYTHONPATH=. python -m pytest tests
